### ISSUE TITLE
Issue while passing permit and placing an order

### ISSUE THREAD

**Issue by coderguy1998** [1inch/fusion-sdk#11]
I have created a permit for USDC using @1inch/permit-signed-approvals-utils which was working while I'm using limit order protocol to place limit orders but the same permit functionality is not working for fusion sdk and I'm getting NotEnoughBalanceOrAllowance 400 error. Can you please share some example on how it is being done on the 1Inch's frontend or if there's anything specific that needs to be done for fusion-sdk while using permits? @k06a @ZumZoom @deacix

**Comment by coderguy1998** [comment]
<img width="648" alt="image" src="https://user-images.githubusercontent.com/59956876/219296100-e6b6d324-50e0-4d88-8908-6082afbfd9ef.png">
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/59956876/219296221-86257950-fc54-4bf0-a5ee-2bc952f9fec3.png">

**Comment by krboktv** [comment]
Hi! We will create an example for you in the coming days 👍

**Comment by coderguy1998** [comment]
Hey @krboktv I have already integrated the SDK and I would be needing it ASAP because my app would be going live soon so can you share any library or code snippet you people are using for generating the permit calldata? Thanks

**Comment by krboktv** [comment]
I think I know your issue: as for `placeOrder`, when you provide `permit` field there, you need to pass `permit` as `tokenAddress + permitCallData.substring(2)`. I hope this helps

**Comment by krboktv** [comment]
But as for `getQuote` you need to keep it as it is

**Comment by coderguy1998** [comment]
I don't think so that's the issue because I copied the permit from the 1Inch App and the permit generated from the code (with changes you have suggested) and they don't match. Passing the permit generated by the 1Inch App works but that isn't dynamic and I need to hardcode it.

**Comment by krboktv** [comment]
@coderguy1998 Permit was missed in order creation in `placeOrder` function. The fix is here: https://github.com/1inch/fusion-sdk/commit/5574200901c36939d407d160ba03310a20709513

Also, check out permit usage examples here: https://github.com/1inch/fusion-resolver-example/blob/main/test/Settlement.ts#L156

New npm version has been released: v0.0.7

**Comment by coderguy1998** [comment]
Thanks!!! I guess the placeOrder not having a permit was a bug? But thanks for the fix. Apart from that there is an issue with the SDK itself because internally there is use of @noble package I guess within the metamask/eth-sig-util which basically is breaking an optimised angular build (production build) the error https://github.com/paulmillr/noble-ed25519/issues/23 something similar to this. Did you guys face any similar issues?

**Comment by coderguy1998** [comment]
The latest version of metamask/eth-sig-lib being 5.0.2 breaks the SDK in prod but the same package being used in limit order protocol library with version 4 doesn't so please take a look into it whenever you have time. Thanks.
