### ISSUE TITLE
Support network polygon (137)

### ISSUE THREAD

**Issue by matyukhin-maxim** [1inch/fusion-sdk#23]
Starting service for Polygon network

```js
    const ws = new WebSocketApi({
      url: 'wss://fusion.1inch.io/ws',
      network: NetworkEnum.POLYGON,
    });
```
fail with error 400

```
    Error: Unexpected server response: 400
    at ClientRequest.<anonymous> (./node_modules/@1inch/fusion-sdk/node_modules/ws/lib/websocket.js:889:7)
```

Etherium and Binance works fine.

**Comment by frolovdev** [comment]
Thank you for your issue, we are on it and try to deliver the fix as fast as possible

**Comment by frolovdev** [comment]
Fixed

The problem was on our side on the infrastructure level, right now you can try on your own directly with an api call
```
wss://fusion.1inch.io/ws/v1.0/137
```

 or through sdk
