### ISSUE TITLE
randomInt is not a function

### ISSUE THREAD

**Issue by tenx-jeff** [1inch/fusion-sdk#26]
When calling `sdk.PlaceOrder()` it's throwing 

<img width="802" alt="Screenshot 2023-04-10 at 8 11 30 PM" src="https://user-images.githubusercontent.com/30624018/230899294-0e937bb9-4637-4d25-8a65-bfe1420f1a54.png">

I ran it on node versions 16 and 19.

**Comment by frolovdev** [comment]
Hey, thank you for reaching out, looks like you are trying to work with the lib in a browser, which was not in mind when we started to develop it. As a fast workaround try to provide salt from the outside using any random generation lib, better to use something with good entropy (not Math.random) like in this example

```
function randomString(length) {
  var bytes = new Uint8Array(length);
  var result = [];
  var charset =
    '123456789';

  let cryptoObj = window.crypto;
  if (!cryptoObj) {
     // use some external npm library here if you need to support old browsers
    return null;
  }

  var random = cryptoObj.getRandomValues(bytes);

  for (var a = 0; a < random.length; a++) {
    result.push(charset[random[a] % charset.length]);
  }

  return result.join('');
}
```

**Comment by tenx-jeff** [comment]
thanks for the fast response! Saw your PR, hope this can be included in your next release :)
